# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PositionGetter
                                 A QGIS plugin
 fetch longtitude,latitude
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-11
        copyright            : (C) 2022 by SUTPC
        email                : 1975676721@qq.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PositionGetter class from file PositionGetter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .position_fetch import PositionGetter
    return PositionGetter(iface)
